"""
Curated list of Pokemon TCG sealed products.
Auto-generated from TCGPlayer catalog + manually maintained.
Images: landing/public/sealed/<id>.jpg (400x558, TCGPlayer CDN).
"""

SEALED_PRODUCTS: list[dict] = [
    # ── Arceus ──────────────────────────────────────────────────────
    {
        "id": "arceus-booster-box",
        "en": "Arceus Booster Box",
        "aliases": ["arceus", "arceus booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Arceus",
        "image_url": "/sealed/arceus-booster-box.jpg",
        "tcgplayer_id": 98593,
    },
    # ── Base Set ────────────────────────────────────────────────────
    {
        "id": "base-set-booster-box",
        "en": "Base Set Booster Box [Revised Unlimited Edition]",
        "aliases": ["base set", "base set booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Base Set",
        "image_url": "/sealed/base-set-booster-box.jpg",
        "tcgplayer_id": 185731,
    },
    # ── Base Set (Shadowless) ───────────────────────────────────────
    {
        "id": "base-set-shadowless-booster-box",
        "en": "Pokemon Base Set (Shadowless) [1st Edition] Booster Box",
        "aliases": ["pokemon base set", "pokemon base set booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Base Set (Shadowless)",
        "image_url": "/sealed/base-set-shadowless-booster-box.jpg",
        "tcgplayer_id": 107596,
    },
    # ── Base Set 2 ──────────────────────────────────────────────────
    {
        "id": "base-set-2-booster-box",
        "en": "Base Set 2 Booster Box",
        "aliases": ["base set 2", "base set 2 booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Base Set 2",
        "image_url": "/sealed/base-set-2-booster-box.jpg",
        "tcgplayer_id": 107610,
    },
    # ── Black and White ─────────────────────────────────────────────
    {
        "id": "black-and-white-booster-box",
        "en": "Black and White Booster Box",
        "aliases": ["black and white", "black and white booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Black and White",
        "image_url": "/sealed/black-and-white-booster-box.jpg",
        "tcgplayer_id": 98552,
    },
    # ── Boundaries Crossed ──────────────────────────────────────────
    {
        "id": "boundaries-crossed-booster-box",
        "en": "Boundaries Crossed Booster Box",
        "aliases": ["boundaries crossed", "boundaries crossed booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Boundaries Crossed",
        "image_url": "/sealed/boundaries-crossed-booster-box.jpg",
        "tcgplayer_id": 98555,
    },
    # ── Call of Legends ─────────────────────────────────────────────
    {
        "id": "call-of-legends-booster-box",
        "en": "Call of Legends Booster Box",
        "aliases": ["call of legends", "call of legends booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Call of Legends",
        "image_url": "/sealed/call-of-legends-booster-box.jpg",
        "tcgplayer_id": 98514,
    },
    # ── Celebrations ────────────────────────────────────────────────
    {
        "id": "celebrations-etb",
        "en": "Celebrations Elite Trainer Box",
        "aliases": ["celebrations", "celebrations etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Celebrations",
        "image_url": "/sealed/celebrations-etb.jpg",
        "tcgplayer_id": 242811,
    },
    # ── Champion's Path ─────────────────────────────────────────────
    {
        "id": "champion-s-path-etb",
        "en": "Champion's Path Elite Trainer Box",
        "aliases": ["champion's path", "champion's path etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Champion's Path",
        "image_url": "/sealed/champion-s-path-etb.jpg",
        "tcgplayer_id": 218791,
    },
    # ── Crown Zenith ────────────────────────────────────────────────
    {
        "id": "crown-zenith-etb",
        "en": "Crown Zenith Elite Trainer Box",
        "aliases": ["crown zenith", "crown zenith etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Crown Zenith",
        "image_url": "/sealed/crown-zenith-etb.jpg",
        "tcgplayer_id": 453470,
    },
    # ── Crystal Guardians ───────────────────────────────────────────
    {
        "id": "crystal-guardians-booster-box",
        "en": "Crystal Guardians Booster Box",
        "aliases": ["crystal guardians", "crystal guardians booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Crystal Guardians",
        "image_url": "/sealed/crystal-guardians-booster-box.jpg",
        "tcgplayer_id": 98567,
    },
    # ── Dark Explorers ──────────────────────────────────────────────
    {
        "id": "dark-explorers-booster-box",
        "en": "Dark Explorers Booster Box",
        "aliases": ["dark explorers", "dark explorers booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Dark Explorers",
        "image_url": "/sealed/dark-explorers-booster-box.jpg",
        "tcgplayer_id": 98520,
    },
    # ── Delta Species ───────────────────────────────────────────────
    {
        "id": "delta-species-booster-box",
        "en": "Delta Species Booster Box",
        "aliases": ["delta species", "delta species booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Delta Species",
        "image_url": "/sealed/delta-species-booster-box.jpg",
        "tcgplayer_id": 98943,
    },
    # ── Deoxys ──────────────────────────────────────────────────────
    {
        "id": "deoxys-booster-box",
        "en": "Deoxys Booster Box",
        "aliases": ["deoxys", "deoxys booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Deoxys",
        "image_url": "/sealed/deoxys-booster-box.jpg",
        "tcgplayer_id": 98563,
    },
    # ── Diamond and Pearl ───────────────────────────────────────────
    {
        "id": "diamond-and-pearl-booster-box",
        "en": "Diamond and Pearl Booster Box",
        "aliases": ["diamond and pearl", "diamond and pearl booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Diamond and Pearl",
        "image_url": "/sealed/diamond-and-pearl-booster-box.jpg",
        "tcgplayer_id": 98524,
    },
    # ── Dragon ──────────────────────────────────────────────────────
    {
        "id": "dragon-booster-box",
        "en": "EX Dragon Booster Box",
        "aliases": ["ex dragon", "ex dragon booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Dragon",
        "image_url": "/sealed/dragon-booster-box.jpg",
        "tcgplayer_id": 98518,
    },
    # ── Dragon Frontiers ────────────────────────────────────────────
    {
        "id": "dragon-frontiers-booster-box",
        "en": "Dragon Frontiers Booster Box",
        "aliases": ["dragon frontiers", "dragon frontiers booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Dragon Frontiers",
        "image_url": "/sealed/dragon-frontiers-booster-box.jpg",
        "tcgplayer_id": 98532,
    },
    # ── Dragon Majesty ──────────────────────────────────────────────
    {
        "id": "dragon-majesty-etb",
        "en": "Dragon Majesty Elite Trainer Box",
        "aliases": ["dragon majesty", "dragon majesty etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Dragon Majesty",
        "image_url": "/sealed/dragon-majesty-etb.jpg",
        "tcgplayer_id": 173393,
    },
    # ── Dragons Exalted ─────────────────────────────────────────────
    {
        "id": "dragons-exalted-booster-box",
        "en": "Dragons Exalted Booster Box",
        "aliases": ["dragons exalted", "dragons exalted booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Dragons Exalted",
        "image_url": "/sealed/dragons-exalted-booster-box.jpg",
        "tcgplayer_id": 98540,
    },
    # ── Emerald ─────────────────────────────────────────────────────
    {
        "id": "emerald-booster-box",
        "en": "Emerald Booster Box",
        "aliases": ["emerald", "emerald booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Emerald",
        "image_url": "/sealed/emerald-booster-box.jpg",
        "tcgplayer_id": 98547,
    },
    # ── Emerging Powers ─────────────────────────────────────────────
    {
        "id": "emerging-powers-booster-box",
        "en": "Emerging Powers Booster Box",
        "aliases": ["emerging powers", "emerging powers booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Emerging Powers",
        "image_url": "/sealed/emerging-powers-booster-box.jpg",
        "tcgplayer_id": 98548,
    },
    # ── FireRed & LeafGreen ─────────────────────────────────────────
    {
        "id": "firered-leafgreen-booster-box",
        "en": "FireRed & LeafGreen Booster Box",
        "aliases": ["firered & leafgreen", "firered & leafgreen booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "FireRed & LeafGreen",
        "image_url": "/sealed/firered-leafgreen-booster-box.jpg",
        "tcgplayer_id": 98945,
    },
    # ── Fossil ──────────────────────────────────────────────────────
    {
        "id": "fossil-booster-box",
        "en": "Pokemon Fossil [Unlimited Edition] Booster Box",
        "aliases": ["pokemon fossil", "pokemon fossil booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Fossil",
        "image_url": "/sealed/fossil-booster-box.jpg",
        "tcgplayer_id": 107600,
    },
    # ── Generations ─────────────────────────────────────────────────
    {
        "id": "generations-etb",
        "en": "Generations Elite Trainer Box",
        "aliases": ["generations", "generations etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Generations",
        "image_url": "/sealed/generations-etb.jpg",
        "tcgplayer_id": 123741,
    },
    # ── Great Encounters ────────────────────────────────────────────
    {
        "id": "great-encounters-booster-box",
        "en": "Great Encounters Booster Box",
        "aliases": ["great encounters", "great encounters booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Great Encounters",
        "image_url": "/sealed/great-encounters-booster-box.jpg",
        "tcgplayer_id": 98544,
    },
    # ── Gym Challenge ───────────────────────────────────────────────
    {
        "id": "gym-challenge-booster-box",
        "en": "Gym Challenge Booster Box [1st Edition]",
        "aliases": ["gym challenge", "gym challenge booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Gym Challenge",
        "image_url": "/sealed/gym-challenge-booster-box.jpg",
        "tcgplayer_id": 276588,
    },
    # ── Gym Heroes ──────────────────────────────────────────────────
    {
        "id": "gym-heroes-booster-box",
        "en": "Gym Heroes Booster Box [1st Edition]",
        "aliases": ["gym heroes", "gym heroes booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Gym Heroes",
        "image_url": "/sealed/gym-heroes-booster-box.jpg",
        "tcgplayer_id": 208707,
    },
    # ── HeartGold SoulSilver ────────────────────────────────────────
    {
        "id": "heartgold-soulsilver-booster-box",
        "en": "HeartGold SoulSilver Booster Box",
        "aliases": ["heartgold soulsilver", "heartgold soulsilver booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "HeartGold SoulSilver",
        "image_url": "/sealed/heartgold-soulsilver-booster-box.jpg",
        "tcgplayer_id": 98531,
    },
    # ── Hidden Fates ────────────────────────────────────────────────
    {
        "id": "hidden-fates-etb",
        "en": "Hidden Fates Elite Trainer Box",
        "aliases": ["hidden fates", "hidden fates etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Hidden Fates",
        "image_url": "/sealed/hidden-fates-etb.jpg",
        "tcgplayer_id": 194729,
    },
    # ── Hidden Legends ──────────────────────────────────────────────
    {
        "id": "hidden-legends-booster-box",
        "en": "Hidden Legends Booster Box",
        "aliases": ["hidden legends", "hidden legends booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Hidden Legends",
        "image_url": "/sealed/hidden-legends-booster-box.jpg",
        "tcgplayer_id": 98596,
    },
    # ── Holon Phantoms ──────────────────────────────────────────────
    {
        "id": "holon-phantoms-booster-box",
        "en": "Holon Phantoms Booster Box",
        "aliases": ["holon phantoms", "holon phantoms booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Holon Phantoms",
        "image_url": "/sealed/holon-phantoms-booster-box.jpg",
        "tcgplayer_id": 98523,
    },
    # ── Jungle ──────────────────────────────────────────────────────
    {
        "id": "jungle-booster-box",
        "en": "Jungle Booster Box [1st Edition]",
        "aliases": ["jungle", "jungle booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Jungle",
        "image_url": "/sealed/jungle-booster-box.jpg",
        "tcgplayer_id": 107598,
    },
    # ── Legend Maker ────────────────────────────────────────────────
    {
        "id": "legend-maker-booster-box",
        "en": "Legend Maker Booster Box",
        "aliases": ["legend maker", "legend maker booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Legend Maker",
        "image_url": "/sealed/legend-maker-booster-box.jpg",
        "tcgplayer_id": 98556,
    },
    # ── Legendary Treasures ─────────────────────────────────────────
    {
        "id": "legendary-treasures-booster-box",
        "en": "Legendary Treasures Booster Box",
        "aliases": ["legendary treasures", "legendary treasures booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Legendary Treasures",
        "image_url": "/sealed/legendary-treasures-booster-box.jpg",
        "tcgplayer_id": 98580,
    },
    # ── Legends Awakened ────────────────────────────────────────────
    {
        "id": "legends-awakened-booster-box",
        "en": "Legends Awakened Booster Box",
        "aliases": ["legends awakened", "legends awakened booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Legends Awakened",
        "image_url": "/sealed/legends-awakened-booster-box.jpg",
        "tcgplayer_id": 98536,
    },
    # ── Mega Evolution ──────────────────────────────────────────────
    {
        "id": "me-mega-evolution-booster-box",
        "en": "Mega Evolution Booster Box",
        "aliases": ["mega evolution", "mega evolution booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Mega Evolution",
        "image_url": "/sealed/me-mega-evolution-booster-box.jpg",
        "tcgplayer_id": 644298,
    },
    {
        "id": "me-mega-evolution-etb",
        "en": "Mega Evolution Elite Trainer Box [Mega Gardevoir]",
        "aliases": ["mega evolution", "mega evolution etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Mega Evolution",
        "image_url": "/sealed/me-mega-evolution-etb.jpg",
        "tcgplayer_id": 644279,
    },
    # ── Phantasmal Flames ───────────────────────────────────────────
    {
        "id": "me-phantasmal-flames-booster-box",
        "en": "Phantasmal Flames Booster Box",
        "aliases": ["phantasmal flames", "phantasmal flames booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Phantasmal Flames",
        "image_url": "/sealed/me-phantasmal-flames-booster-box.jpg",
        "tcgplayer_id": 654137,
    },
    {
        "id": "me-phantasmal-flames-etb",
        "en": "Phantasmal Flames Elite Trainer Box",
        "aliases": ["phantasmal flames", "phantasmal flames etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Phantasmal Flames",
        "image_url": "/sealed/me-phantasmal-flames-etb.jpg",
        "tcgplayer_id": 654136,
    },
    # ── Perfect Order ───────────────────────────────────────────────
    {
        "id": "me-perfect-order-booster-box",
        "en": "Perfect Order Booster Box",
        "aliases": ["perfect order", "perfect order booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Perfect Order",
        "image_url": "/sealed/me-perfect-order-booster-box.jpg",
        "tcgplayer_id": 672394,
    },
    {
        "id": "me-perfect-order-etb",
        "en": "Perfect Order Elite Trainer Box",
        "aliases": ["perfect order", "perfect order etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Perfect Order",
        "image_url": "/sealed/me-perfect-order-etb.jpg",
        "tcgplayer_id": 672401,
    },
    # ── Chaos Rising ────────────────────────────────────────────────
    {
        "id": "me-chaos-rising-booster-box",
        "en": "Chaos Rising Booster Box",
        "aliases": ["chaos rising", "chaos rising booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Chaos Rising",
        "image_url": "/sealed/me-chaos-rising-booster-box.jpg",
        "tcgplayer_id": 684444,
    },
    {
        "id": "me-chaos-rising-etb",
        "en": "Chaos Rising Elite Trainer Box",
        "aliases": ["chaos rising", "chaos rising etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Chaos Rising",
        "image_url": "/sealed/me-chaos-rising-etb.jpg",
        "tcgplayer_id": 684450,
    },
    # ── Ascended Heroes ─────────────────────────────────────────────
    {
        "id": "me-ascended-heroes-etb",
        "en": "Ascended Heroes Elite Trainer Box",
        "aliases": ["ascended heroes", "ascended heroes etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Ascended Heroes",
        "image_url": "/sealed/me-ascended-heroes-etb.jpg",
        "tcgplayer_id": 668496,
    },
    # ── Majestic Dawn ───────────────────────────────────────────────
    {
        "id": "majestic-dawn-booster-box",
        "en": "Majestic Dawn Booster Box",
        "aliases": ["majestic dawn", "majestic dawn booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Majestic Dawn",
        "image_url": "/sealed/majestic-dawn-booster-box.jpg",
        "tcgplayer_id": 98584,
    },
    # ── Mysterious Treasures ────────────────────────────────────────
    {
        "id": "mysterious-treasures-booster-box",
        "en": "Mysterious Treasures Booster Box",
        "aliases": ["mysterious treasures", "mysterious treasures booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Mysterious Treasures",
        "image_url": "/sealed/mysterious-treasures-booster-box.jpg",
        "tcgplayer_id": 98560,
    },
    # ── Neo Destiny ─────────────────────────────────────────────────
    {
        "id": "neo-destiny-booster-box",
        "en": "Neo Destiny Booster Box [1st Edition]",
        "aliases": ["neo destiny", "neo destiny booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Neo Destiny",
        "image_url": "/sealed/neo-destiny-booster-box.jpg",
        "tcgplayer_id": 563754,
    },
    # ── Neo Genesis ─────────────────────────────────────────────────
    {
        "id": "neo-genesis-booster-box",
        "en": "Neo Genesis Booster Box [1st Edition]",
        "aliases": ["neo genesis", "neo genesis booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Neo Genesis",
        "image_url": "/sealed/neo-genesis-booster-box.jpg",
        "tcgplayer_id": 193334,
    },
    # ── Neo Revelation ──────────────────────────────────────────────
    {
        "id": "neo-revelation-booster-box",
        "en": "Neo Revelation Booster Box [1st Edition]",
        "aliases": ["neo revelation", "neo revelation booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Neo Revelation",
        "image_url": "/sealed/neo-revelation-booster-box.jpg",
        "tcgplayer_id": 634445,
    },
    # ── Next Destinies ──────────────────────────────────────────────
    {
        "id": "next-destinies-booster-box",
        "en": "Next Destinies Booster Box",
        "aliases": ["next destinies", "next destinies booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Next Destinies",
        "image_url": "/sealed/next-destinies-booster-box.jpg",
        "tcgplayer_id": 98539,
    },
    # ── Noble Victories ─────────────────────────────────────────────
    {
        "id": "noble-victories-booster-box",
        "en": "Noble Victories Booster Box",
        "aliases": ["noble victories", "noble victories booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Noble Victories",
        "image_url": "/sealed/noble-victories-booster-box.jpg",
        "tcgplayer_id": 98571,
    },
    # ── Plasma Blast ────────────────────────────────────────────────
    {
        "id": "plasma-blast-booster-box",
        "en": "Plasma Blast Booster Box",
        "aliases": ["plasma blast", "plasma blast booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Plasma Blast",
        "image_url": "/sealed/plasma-blast-booster-box.jpg",
        "tcgplayer_id": 98572,
    },
    # ── Plasma Freeze ───────────────────────────────────────────────
    {
        "id": "plasma-freeze-booster-box",
        "en": "Plasma Freeze Booster Box",
        "aliases": ["plasma freeze", "plasma freeze booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Plasma Freeze",
        "image_url": "/sealed/plasma-freeze-booster-box.jpg",
        "tcgplayer_id": 98516,
    },
    # ── Plasma Storm ────────────────────────────────────────────────
    {
        "id": "plasma-storm-booster-box",
        "en": "Plasma Storm Booster Box",
        "aliases": ["plasma storm", "plasma storm booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Plasma Storm",
        "image_url": "/sealed/plasma-storm-booster-box.jpg",
        "tcgplayer_id": 98527,
    },
    # ── Platinum ────────────────────────────────────────────────────
    {
        "id": "platinum-booster-box",
        "en": "Platinum Booster Box",
        "aliases": ["platinum", "platinum booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Platinum",
        "image_url": "/sealed/platinum-booster-box.jpg",
        "tcgplayer_id": 98592,
    },
    # ── Pokemon GO ──────────────────────────────────────────────────
    {
        "id": "pokemon-go-etb",
        "en": "Pokemon GO Elite Trainer Box",
        "aliases": ["pokemon go", "pokemon go etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Pokemon GO",
        "image_url": "/sealed/pokemon-go-etb.jpg",
        "tcgplayer_id": 270708,
    },
    # ── Power Keepers ───────────────────────────────────────────────
    {
        "id": "power-keepers-booster-box",
        "en": "Power Keepers Booster Box",
        "aliases": ["power keepers", "power keepers booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Power Keepers",
        "image_url": "/sealed/power-keepers-booster-box.jpg",
        "tcgplayer_id": 98528,
    },
    # ── Rising Rivals ───────────────────────────────────────────────
    {
        "id": "rising-rivals-booster-box",
        "en": "Rising Rivals Booster Box",
        "aliases": ["rising rivals", "rising rivals booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Rising Rivals",
        "image_url": "/sealed/rising-rivals-booster-box.jpg",
        "tcgplayer_id": 98543,
    },
    # ── Ruby and Sapphire ───────────────────────────────────────────
    {
        "id": "ruby-and-sapphire-booster-box",
        "en": "Ruby and Sapphire Booster Box",
        "aliases": ["ruby and sapphire", "ruby and sapphire booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Ruby and Sapphire",
        "image_url": "/sealed/ruby-and-sapphire-booster-box.jpg",
        "tcgplayer_id": 98559,
    },
    # ── SM - Burning Shadows ────────────────────────────────────────
    {
        "id": "sm-burning-shadows-booster-box",
        "en": "Burning Shadows Booster Box",
        "aliases": ["burning shadows", "burning shadows booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "SM - Burning Shadows",
        "image_url": "/sealed/sm-burning-shadows-booster-box.jpg",
        "tcgplayer_id": 133773,
    },
    {
        "id": "sm-burning-shadows-etb",
        "en": "Burning Shadows Elite Trainer Box",
        "aliases": ["burning shadows", "burning shadows etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "SM - Burning Shadows",
        "image_url": "/sealed/sm-burning-shadows-etb.jpg",
        "tcgplayer_id": 133776,
    },
    # ── SM - Celestial Storm ────────────────────────────────────────
    {
        "id": "sm-celestial-storm-booster-box",
        "en": "Celestial Storm Booster Box",
        "aliases": ["celestial storm", "celestial storm booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "SM - Celestial Storm",
        "image_url": "/sealed/sm-celestial-storm-booster-box.jpg",
        "tcgplayer_id": 170273,
    },
    {
        "id": "sm-celestial-storm-etb",
        "en": "Celestial Storm Elite Trainer Box",
        "aliases": ["celestial storm", "celestial storm etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "SM - Celestial Storm",
        "image_url": "/sealed/sm-celestial-storm-etb.jpg",
        "tcgplayer_id": 170277,
    },
    # ── SM - Cosmic Eclipse ─────────────────────────────────────────
    {
        "id": "sm-cosmic-eclipse-booster-box",
        "en": "Cosmic Eclipse Booster Box",
        "aliases": ["cosmic eclipse", "cosmic eclipse booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "SM - Cosmic Eclipse",
        "image_url": "/sealed/sm-cosmic-eclipse-booster-box.jpg",
        "tcgplayer_id": 199261,
    },
    {
        "id": "sm-cosmic-eclipse-etb",
        "en": "Cosmic Eclipse Elite Trainer Box",
        "aliases": ["cosmic eclipse", "cosmic eclipse etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "SM - Cosmic Eclipse",
        "image_url": "/sealed/sm-cosmic-eclipse-etb.jpg",
        "tcgplayer_id": 199308,
    },
    # ── SM - Crimson Invasion ───────────────────────────────────────
    {
        "id": "sm-crimson-invasion-booster-box",
        "en": "Crimson Invasion Booster Box",
        "aliases": ["crimson invasion", "crimson invasion booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "SM - Crimson Invasion",
        "image_url": "/sealed/sm-crimson-invasion-booster-box.jpg",
        "tcgplayer_id": 146995,
    },
    {
        "id": "sm-crimson-invasion-etb",
        "en": "Crimson Invasion Elite Trainer Box",
        "aliases": ["crimson invasion", "crimson invasion etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "SM - Crimson Invasion",
        "image_url": "/sealed/sm-crimson-invasion-etb.jpg",
        "tcgplayer_id": 149377,
    },
    # ── SM - Forbidden Light ────────────────────────────────────────
    {
        "id": "sm-forbidden-light-booster-box",
        "en": "Forbidden Light Booster Box",
        "aliases": ["forbidden light", "forbidden light booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "SM - Forbidden Light",
        "image_url": "/sealed/sm-forbidden-light-booster-box.jpg",
        "tcgplayer_id": 164296,
    },
    {
        "id": "sm-forbidden-light-etb",
        "en": "Forbidden Light Elite Trainer Box",
        "aliases": ["forbidden light", "forbidden light etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "SM - Forbidden Light",
        "image_url": "/sealed/sm-forbidden-light-etb.jpg",
        "tcgplayer_id": 164303,
    },
    # ── SM - Guardians Rising ───────────────────────────────────────
    {
        "id": "sm-guardians-rising-booster-box",
        "en": "Guardians Rising Booster Box",
        "aliases": ["guardians rising", "guardians rising booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "SM - Guardians Rising",
        "image_url": "/sealed/sm-guardians-rising-booster-box.jpg",
        "tcgplayer_id": 129888,
    },
    {
        "id": "sm-guardians-rising-etb",
        "en": "Guardians Rising Elite Trainer Box",
        "aliases": ["guardians rising", "guardians rising etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "SM - Guardians Rising",
        "image_url": "/sealed/sm-guardians-rising-etb.jpg",
        "tcgplayer_id": 129890,
    },
    # ── SM - Lost Thunder ───────────────────────────────────────────
    {
        "id": "sm-lost-thunder-booster-box",
        "en": "Lost Thunder Booster Box",
        "aliases": ["lost thunder", "lost thunder booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "SM - Lost Thunder",
        "image_url": "/sealed/sm-lost-thunder-booster-box.jpg",
        "tcgplayer_id": 175509,
    },
    {
        "id": "sm-lost-thunder-etb",
        "en": "Lost Thunder Elite Trainer Box",
        "aliases": ["lost thunder", "lost thunder etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "SM - Lost Thunder",
        "image_url": "/sealed/sm-lost-thunder-etb.jpg",
        "tcgplayer_id": 175511,
    },
    # ── SM - Team Up ────────────────────────────────────────────────
    {
        "id": "sm-team-up-booster-box",
        "en": "Team Up Booster Box",
        "aliases": ["team up", "team up booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "SM - Team Up",
        "image_url": "/sealed/sm-team-up-booster-box.jpg",
        "tcgplayer_id": 181698,
    },
    {
        "id": "sm-team-up-etb",
        "en": "Team Up Elite Trainer Box",
        "aliases": ["team up", "team up etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "SM - Team Up",
        "image_url": "/sealed/sm-team-up-etb.jpg",
        "tcgplayer_id": 181704,
    },
    # ── SM - Ultra Prism ────────────────────────────────────────────
    {
        "id": "sm-ultra-prism-booster-box",
        "en": "Ultra Prism Booster Box",
        "aliases": ["ultra prism", "ultra prism booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "SM - Ultra Prism",
        "image_url": "/sealed/sm-ultra-prism-booster-box.jpg",
        "tcgplayer_id": 155661,
    },
    {
        "id": "sm-ultra-prism-etb",
        "en": "Ultra Prism Elite Trainer Box [Dawn Wings Necrozma]",
        "aliases": ["ultra prism", "ultra prism etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "SM - Ultra Prism",
        "image_url": "/sealed/sm-ultra-prism-etb.jpg",
        "tcgplayer_id": 155663,
    },
    # ── SM - Unbroken Bonds ─────────────────────────────────────────
    {
        "id": "sm-unbroken-bonds-booster-box",
        "en": "Unbroken Bonds Booster Box",
        "aliases": ["unbroken bonds", "unbroken bonds booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "SM - Unbroken Bonds",
        "image_url": "/sealed/sm-unbroken-bonds-booster-box.jpg",
        "tcgplayer_id": 185717,
    },
    {
        "id": "sm-unbroken-bonds-etb",
        "en": "Unbroken Bonds Elite Trainer Box",
        "aliases": ["unbroken bonds", "unbroken bonds etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "SM - Unbroken Bonds",
        "image_url": "/sealed/sm-unbroken-bonds-etb.jpg",
        "tcgplayer_id": 185719,
    },
    # ── SM - Unified Minds ──────────────────────────────────────────
    {
        "id": "sm-unified-minds-booster-box",
        "en": "Unified Minds Booster Box",
        "aliases": ["unified minds", "unified minds booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "SM - Unified Minds",
        "image_url": "/sealed/sm-unified-minds-booster-box.jpg",
        "tcgplayer_id": 191882,
    },
    {
        "id": "sm-unified-minds-etb",
        "en": "Unified Minds Elite Trainer Box",
        "aliases": ["unified minds", "unified minds etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "SM - Unified Minds",
        "image_url": "/sealed/sm-unified-minds-etb.jpg",
        "tcgplayer_id": 193052,
    },
    # ── SM Base Set ─────────────────────────────────────────────────
    {
        "id": "sm-base-set-booster-box",
        "en": "Sun & Moon Booster Box",
        "aliases": ["sun & moon", "sun & moon booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "SM Base Set",
        "image_url": "/sealed/sm-base-set-booster-box.jpg",
        "tcgplayer_id": 126048,
    },
    {
        "id": "sm-base-set-etb",
        "en": "Sun & Moon Elite Trainer Box [Solgaleo]",
        "aliases": ["sun & moon", "sun & moon etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "SM Base Set",
        "image_url": "/sealed/sm-base-set-etb.jpg",
        "tcgplayer_id": 126089,
    },
    # ── Scarlet & Violet Base Set ───────────────────────────────────
    {
        "id": "sv-scarlet-violet-base-set-booster-box",
        "en": "Scarlet & Violet Booster Box",
        "aliases": ["scarlet & violet", "scarlet & violet booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Scarlet & Violet Base Set",
        "image_url": "/sealed/sv-scarlet-violet-base-set-booster-box.jpg",
        "tcgplayer_id": 476452,
    },
    {
        "id": "sv-scarlet-violet-base-set-etb",
        "en": "Scarlet & Violet Elite Trainer Box [Koraidon]",
        "aliases": ["scarlet & violet", "scarlet & violet etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Scarlet & Violet Base Set",
        "image_url": "/sealed/sv-scarlet-violet-base-set-etb.jpg",
        "tcgplayer_id": 478335,
    },
    # ── Paldea Evolved ──────────────────────────────────────────────
    {
        "id": "sv-paldea-evolved-booster-box",
        "en": "Paldea Evolved Booster Box",
        "aliases": ["paldea evolved", "paldea evolved booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Paldea Evolved",
        "image_url": "/sealed/sv-paldea-evolved-booster-box.jpg",
        "tcgplayer_id": 493975,
    },
    {
        "id": "sv-paldea-evolved-etb",
        "en": "Paldea Evolved Elite Trainer Box",
        "aliases": ["paldea evolved", "paldea evolved etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Paldea Evolved",
        "image_url": "/sealed/sv-paldea-evolved-etb.jpg",
        "tcgplayer_id": 493974,
    },
    # ── Obsidian Flames ─────────────────────────────────────────────
    {
        "id": "sv-obsidian-flames-booster-box",
        "en": "Obsidian Flames Booster Box",
        "aliases": ["obsidian flames", "obsidian flames booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Obsidian Flames",
        "image_url": "/sealed/sv-obsidian-flames-booster-box.jpg",
        "tcgplayer_id": 501257,
    },
    {
        "id": "sv-obsidian-flames-etb",
        "en": "Obsidian Flames Elite Trainer Box",
        "aliases": ["obsidian flames", "obsidian flames etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Obsidian Flames",
        "image_url": "/sealed/sv-obsidian-flames-etb.jpg",
        "tcgplayer_id": 501264,
    },
    # ── Paradox Rift ────────────────────────────────────────────────
    {
        "id": "sv-paradox-rift-booster-box",
        "en": "Paradox Rift Booster Box",
        "aliases": ["paradox rift", "paradox rift booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Paradox Rift",
        "image_url": "/sealed/sv-paradox-rift-booster-box.jpg",
        "tcgplayer_id": 512821,
    },
    {
        "id": "sv-paradox-rift-etb",
        "en": "Paradox Rift Elite Trainer Box [Iron Valiant]",
        "aliases": ["paradox rift", "paradox rift etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Paradox Rift",
        "image_url": "/sealed/sv-paradox-rift-etb.jpg",
        "tcgplayer_id": 512813,
    },
    # ── Temporal Forces ─────────────────────────────────────────────
    {
        "id": "sv-temporal-forces-booster-box",
        "en": "Temporal Forces Booster Box",
        "aliases": ["temporal forces", "temporal forces booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Temporal Forces",
        "image_url": "/sealed/sv-temporal-forces-booster-box.jpg",
        "tcgplayer_id": 536225,
    },
    {
        "id": "sv-temporal-forces-etb",
        "en": "Temporal Forces Elite Trainer Box [Walking Wake]",
        "aliases": ["temporal forces", "temporal forces etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Temporal Forces",
        "image_url": "/sealed/sv-temporal-forces-etb.jpg",
        "tcgplayer_id": 532845,
    },
    # ── Twilight Masquerade ─────────────────────────────────────────
    {
        "id": "sv-twilight-masquerade-booster-box",
        "en": "Twilight Masquerade Booster Box",
        "aliases": ["twilight masquerade", "twilight masquerade booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Twilight Masquerade",
        "image_url": "/sealed/sv-twilight-masquerade-booster-box.jpg",
        "tcgplayer_id": 543846,
    },
    {
        "id": "sv-twilight-masquerade-etb",
        "en": "Twilight Masquerade Elite Trainer Box",
        "aliases": ["twilight masquerade", "twilight masquerade etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Twilight Masquerade",
        "image_url": "/sealed/sv-twilight-masquerade-etb.jpg",
        "tcgplayer_id": 543845,
    },
    # ── Stellar Crown ───────────────────────────────────────────────
    {
        "id": "sv-stellar-crown-booster-box",
        "en": "Stellar Crown Booster Box",
        "aliases": ["stellar crown", "stellar crown booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Stellar Crown",
        "image_url": "/sealed/sv-stellar-crown-booster-box.jpg",
        "tcgplayer_id": 557354,
    },
    {
        "id": "sv-stellar-crown-etb",
        "en": "Stellar Crown Elite Trainer Box",
        "aliases": ["stellar crown", "stellar crown etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Stellar Crown",
        "image_url": "/sealed/sv-stellar-crown-etb.jpg",
        "tcgplayer_id": 557350,
    },
    # ── Surging Sparks ──────────────────────────────────────────────
    {
        "id": "sv-surging-sparks-booster-box",
        "en": "Surging Sparks Booster Box",
        "aliases": ["surging sparks", "surging sparks booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Surging Sparks",
        "image_url": "/sealed/sv-surging-sparks-booster-box.jpg",
        "tcgplayer_id": 565606,
    },
    {
        "id": "sv-surging-sparks-etb",
        "en": "Surging Sparks Elite Trainer Box",
        "aliases": ["surging sparks", "surging sparks etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Surging Sparks",
        "image_url": "/sealed/sv-surging-sparks-etb.jpg",
        "tcgplayer_id": 565630,
    },
    # ── Journey Together ────────────────────────────────────────────
    {
        "id": "sv-journey-together-booster-box",
        "en": "Journey Together Booster Box",
        "aliases": ["journey together", "journey together booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Journey Together",
        "image_url": "/sealed/sv-journey-together-booster-box.jpg",
        "tcgplayer_id": 610931,
    },
    {
        "id": "sv-journey-together-etb",
        "en": "Journey Together Elite Trainer Box",
        "aliases": ["journey together", "journey together etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Journey Together",
        "image_url": "/sealed/sv-journey-together-etb.jpg",
        "tcgplayer_id": 610930,
    },
    # ── Destined Rivals ─────────────────────────────────────────────
    {
        "id": "sv-destined-rivals-booster-box",
        "en": "Destined Rivals Booster Box",
        "aliases": ["destined rivals", "destined rivals booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Destined Rivals",
        "image_url": "/sealed/sv-destined-rivals-booster-box.jpg",
        "tcgplayer_id": 624679,
    },
    {
        "id": "sv-destined-rivals-etb",
        "en": "Destined Rivals Elite Trainer Box",
        "aliases": ["destined rivals", "destined rivals etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Destined Rivals",
        "image_url": "/sealed/sv-destined-rivals-etb.jpg",
        "tcgplayer_id": 624676,
    },
    # ── Black Bolt ──────────────────────────────────────────────────
    {
        "id": "sv-black-bolt-etb",
        "en": "Black Bolt Elite Trainer Box",
        "aliases": ["black bolt", "black bolt etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Black Bolt",
        "image_url": "/sealed/sv-black-bolt-etb.jpg",
        "tcgplayer_id": 630686,
    },
    # ── Paldean Fates ───────────────────────────────────────────────
    {
        "id": "sv-paldean-fates-etb",
        "en": "Paldean Fates Elite Trainer Box",
        "aliases": ["paldean fates", "paldean fates etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Paldean Fates",
        "image_url": "/sealed/sv-paldean-fates-etb.jpg",
        "tcgplayer_id": 528040,
    },
    # ── Prismatic Evolutions ────────────────────────────────────────
    {
        "id": "sv-prismatic-evolutions-etb",
        "en": "Prismatic Evolutions Elite Trainer Box",
        "aliases": ["prismatic evolutions", "prismatic evolutions etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Prismatic Evolutions",
        "image_url": "/sealed/sv-prismatic-evolutions-etb.jpg",
        "tcgplayer_id": 593355,
    },
    # ── Scarlet & Violet 151 ────────────────────────────────────────
    {
        "id": "sv-scarlet-violet-151-etb",
        "en": "151 Elite Trainer Box",
        "aliases": ["151", "151 etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Scarlet & Violet 151",
        "image_url": "/sealed/sv-scarlet-violet-151-etb.jpg",
        "tcgplayer_id": 503313,
    },
    # ── Shrouded Fable ──────────────────────────────────────────────
    {
        "id": "sv-shrouded-fable-etb",
        "en": "Shrouded Fable Elite Trainer Box",
        "aliases": ["shrouded fable", "shrouded fable etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Shrouded Fable",
        "image_url": "/sealed/sv-shrouded-fable-etb.jpg",
        "tcgplayer_id": 552999,
    },
    # ── White Flare ─────────────────────────────────────────────────
    {
        "id": "sv-white-flare-etb",
        "en": "White Flare Elite Trainer Box",
        "aliases": ["white flare", "white flare etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "White Flare",
        "image_url": "/sealed/sv-white-flare-etb.jpg",
        "tcgplayer_id": 630689,
    },
    # ── Sword & Shield Base Set ─────────────────────────────────────
    {
        "id": "swsh-sword-shield-base-set-booster-box",
        "en": "Sword & Shield Booster Box",
        "aliases": ["sword & shield", "sword & shield booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Sword & Shield Base Set",
        "image_url": "/sealed/swsh-sword-shield-base-set-booster-box.jpg",
        "tcgplayer_id": 206027,
    },
    {
        "id": "swsh-sword-shield-base-set-etb",
        "en": "Sword & Shield Elite Trainer Box [Zacian]",
        "aliases": ["sword & shield", "sword & shield etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Sword & Shield Base Set",
        "image_url": "/sealed/swsh-sword-shield-base-set-etb.jpg",
        "tcgplayer_id": 206038,
    },
    # ── Rebel Clash ─────────────────────────────────────────────────
    {
        "id": "swsh-rebel-clash-booster-box",
        "en": "Rebel Clash Booster Box",
        "aliases": ["rebel clash", "rebel clash booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Rebel Clash",
        "image_url": "/sealed/swsh-rebel-clash-booster-box.jpg",
        "tcgplayer_id": 210561,
    },
    {
        "id": "swsh-rebel-clash-etb",
        "en": "Rebel Clash Elite Trainer Box",
        "aliases": ["rebel clash", "rebel clash etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Rebel Clash",
        "image_url": "/sealed/swsh-rebel-clash-etb.jpg",
        "tcgplayer_id": 210572,
    },
    # ── Darkness Ablaze ─────────────────────────────────────────────
    {
        "id": "swsh-darkness-ablaze-booster-box",
        "en": "Darkness Ablaze Booster Box",
        "aliases": ["darkness ablaze", "darkness ablaze booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Darkness Ablaze",
        "image_url": "/sealed/swsh-darkness-ablaze-booster-box.jpg",
        "tcgplayer_id": 216853,
    },
    {
        "id": "swsh-darkness-ablaze-etb",
        "en": "Darkness Ablaze Elite Trainer Box",
        "aliases": ["darkness ablaze", "darkness ablaze etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Darkness Ablaze",
        "image_url": "/sealed/swsh-darkness-ablaze-etb.jpg",
        "tcgplayer_id": 216856,
    },
    # ── Vivid Voltage ───────────────────────────────────────────────
    {
        "id": "swsh-vivid-voltage-booster-box",
        "en": "Vivid Voltage Booster Box",
        "aliases": ["vivid voltage", "vivid voltage booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Vivid Voltage",
        "image_url": "/sealed/swsh-vivid-voltage-booster-box.jpg",
        "tcgplayer_id": 221313,
    },
    {
        "id": "swsh-vivid-voltage-etb",
        "en": "Vivid Voltage Elite Trainer Box",
        "aliases": ["vivid voltage", "vivid voltage etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Vivid Voltage",
        "image_url": "/sealed/swsh-vivid-voltage-etb.jpg",
        "tcgplayer_id": 221752,
    },
    # ── Battle Styles ───────────────────────────────────────────────
    {
        "id": "swsh-battle-styles-booster-box",
        "en": "Battle Styles Booster Box",
        "aliases": ["battle styles", "battle styles booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Battle Styles",
        "image_url": "/sealed/swsh-battle-styles-booster-box.jpg",
        "tcgplayer_id": 229277,
    },
    {
        "id": "swsh-battle-styles-etb",
        "en": "Battle Styles Elite Trainer Box [Single Strike Urshifu] (Red)",
        "aliases": ["battle styles", "battle styles etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Battle Styles",
        "image_url": "/sealed/swsh-battle-styles-etb.jpg",
        "tcgplayer_id": 229284,
    },
    # ── Chilling Reign ──────────────────────────────────────────────
    {
        "id": "swsh-chilling-reign-booster-box",
        "en": "Chilling Reign Booster Box",
        "aliases": ["chilling reign", "chilling reign booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Chilling Reign",
        "image_url": "/sealed/swsh-chilling-reign-booster-box.jpg",
        "tcgplayer_id": 236258,
    },
    {
        "id": "swsh-chilling-reign-etb",
        "en": "Chilling Reign Elite Trainer Box [Ice Rider Calyrex]",
        "aliases": ["chilling reign", "chilling reign etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Chilling Reign",
        "image_url": "/sealed/swsh-chilling-reign-etb.jpg",
        "tcgplayer_id": 236260,
    },
    # ── Evolving Skies ──────────────────────────────────────────────
    {
        "id": "swsh-evolving-skies-booster-box",
        "en": "Evolving Skies Booster Box",
        "aliases": ["evolving skies", "evolving skies booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Evolving Skies",
        "image_url": "/sealed/swsh-evolving-skies-booster-box.jpg",
        "tcgplayer_id": 242436,
    },
    {
        "id": "swsh-evolving-skies-etb",
        "en": "Evolving Skies Elite Trainer Box [Flareon/Jolteon/Umbreon/Leafeon]",
        "aliases": ["evolving skies", "evolving skies etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Evolving Skies",
        "image_url": "/sealed/swsh-evolving-skies-etb.jpg",
        "tcgplayer_id": 242434,
    },
    # ── Fusion Strike ───────────────────────────────────────────────
    {
        "id": "swsh-fusion-strike-booster-box",
        "en": "Fusion Strike Booster Box",
        "aliases": ["fusion strike", "fusion strike booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Fusion Strike",
        "image_url": "/sealed/swsh-fusion-strike-booster-box.jpg",
        "tcgplayer_id": 247654,
    },
    {
        "id": "swsh-fusion-strike-etb",
        "en": "Fusion Strike Elite Trainer Box",
        "aliases": ["fusion strike", "fusion strike etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Fusion Strike",
        "image_url": "/sealed/swsh-fusion-strike-etb.jpg",
        "tcgplayer_id": 247671,
    },
    # ── Brilliant Stars ─────────────────────────────────────────────
    {
        "id": "swsh-brilliant-stars-booster-box",
        "en": "Brilliant Stars Booster Box",
        "aliases": ["brilliant stars", "brilliant stars booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Brilliant Stars",
        "image_url": "/sealed/swsh-brilliant-stars-booster-box.jpg",
        "tcgplayer_id": 256141,
    },
    {
        "id": "swsh-brilliant-stars-etb",
        "en": "Brilliant Stars Elite Trainer Box",
        "aliases": ["brilliant stars", "brilliant stars etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Brilliant Stars",
        "image_url": "/sealed/swsh-brilliant-stars-etb.jpg",
        "tcgplayer_id": 256138,
    },
    # ── Astral Radiance ─────────────────────────────────────────────
    {
        "id": "swsh-astral-radiance-booster-box",
        "en": "Astral Radiance Booster Box",
        "aliases": ["astral radiance", "astral radiance booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Astral Radiance",
        "image_url": "/sealed/swsh-astral-radiance-booster-box.jpg",
        "tcgplayer_id": 265519,
    },
    {
        "id": "swsh-astral-radiance-etb",
        "en": "Astral Radiance Elite Trainer Box",
        "aliases": ["astral radiance", "astral radiance etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Astral Radiance",
        "image_url": "/sealed/swsh-astral-radiance-etb.jpg",
        "tcgplayer_id": 265527,
    },
    # ── Lost Origin ─────────────────────────────────────────────────
    {
        "id": "swsh-lost-origin-booster-box",
        "en": "Lost Origin Booster Box",
        "aliases": ["lost origin", "lost origin booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Lost Origin",
        "image_url": "/sealed/swsh-lost-origin-booster-box.jpg",
        "tcgplayer_id": 277324,
    },
    {
        "id": "swsh-lost-origin-etb",
        "en": "Lost Origin Elite Trainer Box",
        "aliases": ["lost origin", "lost origin etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Lost Origin",
        "image_url": "/sealed/swsh-lost-origin-etb.jpg",
        "tcgplayer_id": 277335,
    },
    # ── Silver Tempest ──────────────────────────────────────────────
    {
        "id": "swsh-silver-tempest-booster-box",
        "en": "Silver Tempest Booster Box",
        "aliases": ["silver tempest", "silver tempest booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Silver Tempest",
        "image_url": "/sealed/swsh-silver-tempest-booster-box.jpg",
        "tcgplayer_id": 283389,
    },
    {
        "id": "swsh-silver-tempest-etb",
        "en": "Silver Tempest Elite Trainer Box",
        "aliases": ["silver tempest", "silver tempest etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Silver Tempest",
        "image_url": "/sealed/swsh-silver-tempest-etb.jpg",
        "tcgplayer_id": 283401,
    },
    # ── Sandstorm ───────────────────────────────────────────────────
    {
        "id": "sandstorm-booster-box",
        "en": "Sandstorm Booster Box",
        "aliases": ["sandstorm", "sandstorm booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Sandstorm",
        "image_url": "/sealed/sandstorm-booster-box.jpg",
        "tcgplayer_id": 98564,
    },
    # ── Secret Wonders ──────────────────────────────────────────────
    {
        "id": "secret-wonders-booster-box",
        "en": "Secret Wonders Booster Box",
        "aliases": ["secret wonders", "secret wonders booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Secret Wonders",
        "image_url": "/sealed/secret-wonders-booster-box.jpg",
        "tcgplayer_id": 98568,
    },
    # ── Shining Fates ───────────────────────────────────────────────
    {
        "id": "shining-fates-etb",
        "en": "Shining Fates Elite Trainer Box",
        "aliases": ["shining fates", "shining fates etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Shining Fates",
        "image_url": "/sealed/shining-fates-etb.jpg",
        "tcgplayer_id": 228821,
    },
    # ── Shining Legends ─────────────────────────────────────────────
    {
        "id": "shining-legends-etb",
        "en": "Shining Legends Elite Trainer Box",
        "aliases": ["shining legends", "shining legends etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "Shining Legends",
        "image_url": "/sealed/shining-legends-etb.jpg",
        "tcgplayer_id": 145847,
    },
    # ── Stormfront ──────────────────────────────────────────────────
    {
        "id": "stormfront-booster-box",
        "en": "Stormfront Booster Box",
        "aliases": ["stormfront", "stormfront booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Stormfront",
        "image_url": "/sealed/stormfront-booster-box.jpg",
        "tcgplayer_id": 98588,
    },
    # ── Supreme Victors ─────────────────────────────────────────────
    {
        "id": "supreme-victors-booster-box",
        "en": "Supreme Victors Booster Box",
        "aliases": ["supreme victors", "supreme victors booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Supreme Victors",
        "image_url": "/sealed/supreme-victors-booster-box.jpg",
        "tcgplayer_id": 98575,
    },
    # ── Team Magma vs Team Aqua ─────────────────────────────────────
    {
        "id": "team-magma-vs-team-aqua-booster-box",
        "en": "Team Magma vs Team Aqua Booster Box",
        "aliases": ["team magma vs team aqua", "team magma vs team aqua booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Team Magma vs Team Aqua",
        "image_url": "/sealed/team-magma-vs-team-aqua-booster-box.jpg",
        "tcgplayer_id": 98551,
    },
    # ── Team Rocket ─────────────────────────────────────────────────
    {
        "id": "team-rocket-booster-box",
        "en": "Team Rocket Booster Box [1st Edition]",
        "aliases": ["team rocket", "team rocket booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Team Rocket",
        "image_url": "/sealed/team-rocket-booster-box.jpg",
        "tcgplayer_id": 209436,
    },
    # ── Team Rocket Returns ─────────────────────────────────────────
    {
        "id": "team-rocket-returns-booster-box",
        "en": "Team Rocket Returns Booster Box",
        "aliases": ["team rocket returns", "team rocket returns booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Team Rocket Returns",
        "image_url": "/sealed/team-rocket-returns-booster-box.jpg",
        "tcgplayer_id": 98579,
    },
    # ── Triumphant ──────────────────────────────────────────────────
    {
        "id": "triumphant-booster-box",
        "en": "Triumphant Booster Box",
        "aliases": ["triumphant", "triumphant booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Triumphant",
        "image_url": "/sealed/triumphant-booster-box.jpg",
        "tcgplayer_id": 98535,
    },
    # ── Undaunted ───────────────────────────────────────────────────
    {
        "id": "undaunted-booster-box",
        "en": "Undaunted Booster Box",
        "aliases": ["undaunted", "undaunted booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Undaunted",
        "image_url": "/sealed/undaunted-booster-box.jpg",
        "tcgplayer_id": 98587,
    },
    # ── Unleashed ───────────────────────────────────────────────────
    {
        "id": "unleashed-booster-box",
        "en": "Unleashed Booster Box",
        "aliases": ["unleashed", "unleashed booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Unleashed",
        "image_url": "/sealed/unleashed-booster-box.jpg",
        "tcgplayer_id": 98583,
    },
    # ── Unseen Forces ───────────────────────────────────────────────
    {
        "id": "unseen-forces-booster-box",
        "en": "Unseen Forces Booster Box",
        "aliases": ["unseen forces", "unseen forces booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "Unseen Forces",
        "image_url": "/sealed/unseen-forces-booster-box.jpg",
        "tcgplayer_id": 98576,
    },
    # ── XY - Ancient Origins ────────────────────────────────────────
    {
        "id": "xy-ancient-origins-booster-box",
        "en": "XY Ancient Origins Booster Box",
        "aliases": ["xy ancient origins", "xy ancient origins booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "XY - Ancient Origins",
        "image_url": "/sealed/xy-ancient-origins-booster-box.jpg",
        "tcgplayer_id": 100489,
    },
    {
        "id": "xy-ancient-origins-etb",
        "en": "Ancient Origins Elite Trainer Box",
        "aliases": ["ancient origins", "ancient origins etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "XY - Ancient Origins",
        "image_url": "/sealed/xy-ancient-origins-etb.jpg",
        "tcgplayer_id": 100495,
    },
    # ── XY - BREAKpoint ─────────────────────────────────────────────
    {
        "id": "xy-breakpoint-booster-box",
        "en": "XY BREAKpoint Booster Box",
        "aliases": ["xy breakpoint", "xy breakpoint booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "XY - BREAKpoint",
        "image_url": "/sealed/xy-breakpoint-booster-box.jpg",
        "tcgplayer_id": 111278,
    },
    {
        "id": "xy-breakpoint-etb",
        "en": "XY BREAKpoint Elite Trainer Box",
        "aliases": ["xy breakpoint", "xy breakpoint etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "XY - BREAKpoint",
        "image_url": "/sealed/xy-breakpoint-etb.jpg",
        "tcgplayer_id": 111280,
    },
    # ── XY - BREAKthrough ───────────────────────────────────────────
    {
        "id": "xy-breakthrough-booster-box",
        "en": "XY BREAKthrough Booster Box",
        "aliases": ["xy breakthrough", "xy breakthrough booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "XY - BREAKthrough",
        "image_url": "/sealed/xy-breakthrough-booster-box.jpg",
        "tcgplayer_id": 107101,
    },
    {
        "id": "xy-breakthrough-etb",
        "en": "Elite Trainer Box [Mewtwo X]",
        "aliases": [],
        "type": "sealed",
        "product_type": "etb",
        "set": "XY - BREAKthrough",
        "image_url": "/sealed/xy-breakthrough-etb.jpg",
        "tcgplayer_id": 107106,
    },
    # ── XY - Evolutions ─────────────────────────────────────────────
    {
        "id": "xy-evolutions-booster-box",
        "en": "XY Evolutions Booster Box",
        "aliases": ["xy evolutions", "xy evolutions booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "XY - Evolutions",
        "image_url": "/sealed/xy-evolutions-booster-box.jpg",
        "tcgplayer_id": 123446,
    },
    {
        "id": "xy-evolutions-etb",
        "en": "XY Evolutions Elite Trainer Box [Mega Charizard Y]",
        "aliases": ["xy evolutions", "xy evolutions etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "XY - Evolutions",
        "image_url": "/sealed/xy-evolutions-etb.jpg",
        "tcgplayer_id": 123447,
    },
    # ── XY - Fates Collide ──────────────────────────────────────────
    {
        "id": "xy-fates-collide-booster-box",
        "en": "XY Fates Collide Booster Box",
        "aliases": ["xy fates collide", "xy fates collide booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "XY - Fates Collide",
        "image_url": "/sealed/xy-fates-collide-booster-box.jpg",
        "tcgplayer_id": 117478,
    },
    {
        "id": "xy-fates-collide-etb",
        "en": "Fates Collide Elite Trainer Box",
        "aliases": ["fates collide", "fates collide etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "XY - Fates Collide",
        "image_url": "/sealed/xy-fates-collide-etb.jpg",
        "tcgplayer_id": 118331,
    },
    # ── XY - Flashfire ──────────────────────────────────────────────
    {
        "id": "xy-flashfire-booster-box",
        "en": "Flashfire Booster Box",
        "aliases": ["flashfire", "flashfire booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "XY - Flashfire",
        "image_url": "/sealed/xy-flashfire-booster-box.jpg",
        "tcgplayer_id": 91594,
    },
    # ── XY - Furious Fists ──────────────────────────────────────────
    {
        "id": "xy-furious-fists-booster-box",
        "en": "Furious Fists Booster Box",
        "aliases": ["furious fists", "furious fists booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "XY - Furious Fists",
        "image_url": "/sealed/xy-furious-fists-booster-box.jpg",
        "tcgplayer_id": 92168,
    },
    {
        "id": "xy-furious-fists-etb",
        "en": "Furious Fists Elite Trainer Box",
        "aliases": ["furious fists", "furious fists etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "XY - Furious Fists",
        "image_url": "/sealed/xy-furious-fists-etb.jpg",
        "tcgplayer_id": 95284,
    },
    # ── XY - Phantom Forces ─────────────────────────────────────────
    {
        "id": "xy-phantom-forces-booster-box",
        "en": "XY Phantom Forces Booster Box",
        "aliases": ["xy phantom forces", "xy phantom forces booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "XY - Phantom Forces",
        "image_url": "/sealed/xy-phantom-forces-booster-box.jpg",
        "tcgplayer_id": 94623,
    },
    {
        "id": "xy-phantom-forces-etb",
        "en": "Phantom Forces Elite Trainer Box",
        "aliases": ["phantom forces", "phantom forces etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "XY - Phantom Forces",
        "image_url": "/sealed/xy-phantom-forces-etb.jpg",
        "tcgplayer_id": 97786,
    },
    # ── XY - Primal Clash ───────────────────────────────────────────
    {
        "id": "xy-primal-clash-booster-box",
        "en": "XY Primal Clash Booster Box",
        "aliases": ["xy primal clash", "xy primal clash booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "XY - Primal Clash",
        "image_url": "/sealed/xy-primal-clash-booster-box.jpg",
        "tcgplayer_id": 97750,
    },
    {
        "id": "xy-primal-clash-etb",
        "en": "Elite Trainer Box [Groudon]",
        "aliases": [],
        "type": "sealed",
        "product_type": "etb",
        "set": "XY - Primal Clash",
        "image_url": "/sealed/xy-primal-clash-etb.jpg",
        "tcgplayer_id": 97762,
    },
    # ── XY - Roaring Skies ──────────────────────────────────────────
    {
        "id": "xy-roaring-skies-booster-box",
        "en": "XY Roaring Skies Booster Box",
        "aliases": ["xy roaring skies", "xy roaring skies booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "XY - Roaring Skies",
        "image_url": "/sealed/xy-roaring-skies-booster-box.jpg",
        "tcgplayer_id": 98026,
    },
    {
        "id": "xy-roaring-skies-etb",
        "en": "XY Roaring Skies Elite Trainer Box",
        "aliases": ["xy roaring skies", "xy roaring skies etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "XY - Roaring Skies",
        "image_url": "/sealed/xy-roaring-skies-etb.jpg",
        "tcgplayer_id": 98028,
    },
    # ── XY - Steam Siege ────────────────────────────────────────────
    {
        "id": "xy-steam-siege-booster-box",
        "en": "Steam Siege Booster Box",
        "aliases": ["steam siege", "steam siege booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "XY - Steam Siege",
        "image_url": "/sealed/xy-steam-siege-booster-box.jpg",
        "tcgplayer_id": 120076,
    },
    {
        "id": "xy-steam-siege-etb",
        "en": "Steam Siege Elite Trainer Box",
        "aliases": ["steam siege", "steam siege etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "XY - Steam Siege",
        "image_url": "/sealed/xy-steam-siege-etb.jpg",
        "tcgplayer_id": 120697,
    },
    # ── XY Base Set ─────────────────────────────────────────────────
    {
        "id": "xy-base-set-booster-box",
        "en": "XY Booster Box",
        "aliases": ["xy", "xy booster box"],
        "type": "sealed",
        "product_type": "booster_box",
        "set": "XY Base Set",
        "image_url": "/sealed/xy-base-set-booster-box.jpg",
        "tcgplayer_id": 91601,
    },
    {
        "id": "xy-base-set-etb",
        "en": "XY Elite Trainer Box [Xerneas]",
        "aliases": ["xy", "xy etb"],
        "type": "sealed",
        "product_type": "etb",
        "set": "XY Base Set",
        "image_url": "/sealed/xy-base-set-etb.jpg",
        "tcgplayer_id": 97747,
    },
]

SEALED_BY_ID: dict[str, dict] = {p["id"]: p for p in SEALED_PRODUCTS}


def local_image_path(product: dict) -> str | None:
    """Absolute filesystem path to the product image, for Telegram reply_photo."""
    from pathlib import Path
    if not product.get("image_url"):
        return None
    filename = product["image_url"].lstrip("/")
    root = Path(__file__).parent.parent.parent.parent / "landing" / "public"
    path = root / filename
    return str(path) if path.exists() else None